### ISSUE TITLE
取某一个value 怎么用呢？

### ISSUE THREAD

**Issue by rjzou** [Barenboim/json-parser#2]
json_value_t *json_value_parse(const char *doc);
这里的返回 json_value_t 不是整个json吗？
const char *json_value_string(const json_value_t *val);
再把整个json_value_t 作为参数 去取value 吗？

**Comment by Barenboim** [comment]
我在这个issue里有介绍接口的用法：
https://github.com/sogou/workflow/issues/815
一个json文档，就是对应到一个json value。value有多种类型。你说的string是value的一种，可以通过json_value_type()接口得到value类型。

**Comment by rjzou** [comment]
{
    "userName ": "111111",
    "pwd ": "123456 "
}

用哪个方法get("userName") 的值。

**Comment by Barenboim** [comment]
~~~c
{
    const char *doc = " { ... } ";
    json_value_t *val = json_value_parse(doc);
    json_object_t *obj = json_value_object(val);
    if (obj) 
    {
        const json_value_t *v = json_object_find("userName");
        if (v)
        {
            const char *str = v->json_value_string();  // "111111"
            ....
        }
        ... 
    }
}
~~~

**Comment by rjzou** [comment]
谢谢
