### ISSUE TITLE
About c version

### ISSUE THREAD

**Issue by chanchann** [Barenboim/json-parser#4]
The title is Json Parser in ANSI-C (C89), but I add the flag -std=c89 in makefile, it can't compile.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/27816166/205216417-f1303aa2-6375-4455-80a4-763aecffedf5.png">
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/27816166/205216458-93bf27d6-a6fa-44f1-a884-e9a2d1aaed0b.png">

**Comment by Barenboim** [comment]
Sorry. It's a mistake. 'strdup' is not even a standard C function... I'v updated the code to remove the usage of 'strdup'. And because 'NAN' is a macro defined by IOS C99, we have to upgrade to C99.
https://github.com/Barenboim/json-parser/commits/main

**Comment by MoonChasing** [comment]
`ANSI C` generally refers to `C89`, and it feels a bit strange to indicate `ANSI C (C99)` in README.

**Comment by Barenboim** [comment]
Yes. I will update the discription.
