### ISSUE TITLE
The usefulness of free() in __move_json_value

### ISSUE THREAD

**Issue by MoonChasing** [Barenboim/json-parser#5]
Hello, I want to know the usefulness of  `free()` in `__move_json_value` , especially when type is object or array,
I wonder if there is a memory bug here (I have such doubts, I haven't read the code in too much detail).

**Comment by Barenboim** [comment]
Thank you. It's a bug... The code of removing value from object or array is still untested.
I forgot that __move_json_value will free the 'src' JSON value. I will fix it ASAP.

**Comment by MoonChasing** [comment]
Yes, thx.

**Comment by Barenboim** [comment]
Fix in: https://github.com/Barenboim/json-parser/commit/a2a9a5e10689a85af6015ced4718f68154360cc6

**Comment by MoonChasing** [comment]
So perfect.
